# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: ardoq/ci-docker-front:0.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: rm -rf node_modules
      - run: yarn

      # run tests!
      - run: npm run test:integration
